### ISSUE TITLE
Ffmpeg using copy mode

### ISSUE THREAD

**Issue by 671792320** [marcus-j-davies/node-red-contrib-homekit-preconfigured#7]
As for ffmpeg, it was discussed in the group in the daytime today and found that there was no pressure at all when ffmpeg was set to copy mode.

And I also test normal, CPU load is very low.
![123123](https://user-images.githubusercontent.com/10532894/75878082-00afb380-5e54-11ea-933b-012d37c9fd50.png)
Here are the changes、Yes, you can delete the width and height and run it
const ffmpegInputArgs = ' -map ' + mapvideo + ' -vcodec ' + vcodec + ' -pix_fmt yuv420p -r ' + fps + ' -f rawvideo' + ' ' + additionalCommandline +  ' -b:v ' + vbitrate + 'k' + ' -bufsize ' + vbitrate + 'k' + ' -maxrate ' + vbitrate + 'k' + ' -payload_type 99'

**Comment by marcus-j-davies** [comment]
Yes, you can remove the -vf Attribute so you can use the copy encoder, but it’s a bad idea.

1) The camera may use an encoder  not supported by iOS (some cameras use a multipart jpg stream) and if using copy for such camera - it will not work in iOS) iOS requires MP4, the copy encoder will simply push the raw byte stream to iOS and iOS will likely not work if it’s not an MP4 stream

2) the -vf attribute  is to send the size required by the iOS device, some Apple watches don’t play the stream if it’s not the size requested.

I used the copy encoder once, but it did not work on on my Apple Watch - due to the size not being what was requested, I had an old camera which used multipart jpg which when using copy will not work for iOS

using copy can work, but in most cases it’s out of sheer luck it works.

**Comment by 671792320** [comment]
Yes, but there's no way. Vaapi can't work because of the problem of nodes. My camera's RTSP is H264 encoded, so I can directly copy and skip the transcoding part

In addition, does your project support doorbell and watchdog functions?

**Comment by 671792320** [comment]
![1333](https://user-images.githubusercontent.com/10532894/75883207-9bf95680-5e5d-11ea-8de6-e0719d42fb64.png)

**Comment by marcus-j-davies** [comment]
My node collection has a motion sensor, but no doorbell.

If your referring to the motion sensing offered by some secure home kit cameras - its not something i am looking to implement currently, KhaosT and the other devs are still working on it.

**Comment by 671792320** [comment]
Has your node considered adding audio support

**Comment by marcus-j-davies** [comment]
It did once, but there is only 1 decent audio encoder that is capable of rendering for Apple.
and in order to get that encoder - you have to compile ffmpeg your self using **libfdk-aac**

I also found that when you start encoding the audio - you have to balance a lot of things the bitrate and what not, and you end up with very choppy video/audio

This collection was for my own use originally, hence some of the features were never implemented.
There is something else i am working on for homekit, and this other thing (i have not yet made it public) will supersede this collection.

**Comment by 671792320** [comment]
OK, I'm looking forward to your next work

**Comment by marcus-j-davies** [comment]
Teaser.

**Comment by 671792320** [comment]
When will your next project be released?

I'll see your project then

**Comment by marcus-j-davies** [comment]
its almost ready.
I'm just finishing some of the UI

it will support Node-Red and any other automation software that supports, HTTP, UDP, TCP & 
![dsfds](https://user-images.githubusercontent.com/55892693/75885982-646bb980-5e1f-11ea-9644-7e2455c1b5b9.jpg)
FILE

**Comment by 671792320** [comment]
It looks great!

I'm looking forward to your work

**Comment by marcus-j-davies** [comment]
New Project online!
